apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejsrepo
          image: 444930709892.dkr.ecr.ap-southeast-1.amazonaws.com/nodejsrepo:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
