apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs-ecr
          image: 376476525700.dkr.ecr.us-east-1.amazonaws.com/nodejs-ecr:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
